<?php

require_once "ChiTietMay_OOP.php";
require_once "ChiTietPhuc.php";
require_once "Kho.php";
require_once  "May.php";
require_once "helper.php";

class chiTietDon extends  Chitietmay
{
    private $gia;
    private $khoiLuong;

    public function nhap(){
        parent::nhap();
        $this->gia = helper::inputPrice($this->gia, "Nhap gia: ");
        $this->khoiLuong= helper::inputIn($this->khoiLuong,'Nhap khoi luong: ');
        echo "_____________________"."\n";
    }


    public function xuat()
    {
        parent::xuat(); // TODO: Change the autogenerated stub
        echo "Gia :".number_format($this->gia)." VND \n";
        echo "Khoi luong :".$this->khoiLuong." KG \n";
        echo "========================"."\n";
    }


    public function tinhTien()
    {
        return $this->gia;
    }


    public function tinhKhoiLuong()
    {
        return $this->khoiLuong;
    }

}